name: Testing

on:
  push:
    branches:
      - [master]


jobs:
  pocaz:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        uses: echo "That's just showing"

  pocaz:
    runs-on: window

    steps:
      - name: Print second
        uses: echo "Num 2"

  