name: Testing

on:
  push:
    branches:
      - master


jobs:
  pocaz:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        uses: echo "That's just showing"
  second-pocaz:
    runs-on: windows-latest

    steps:
      - name: Print second
        uses: echo "Num 2"

  