name: deploy to firebase
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check repo
      - uses: actions/checkout@v2

      - name: set up Node.js 
      - uses: actions/setup-node@v2
        with:
          node-version: '24.12.0'
      
      - name: deploy to firebase
        run: /
          npm install -g firebase-tools
          firebase deploy --only hosting --project ${{ secrets.PROJECT_ID }} --token ${{ secrets.ACCESS_TOKEN }}

      